networks:
  transcendence-backend:
    driver: bridge
  app-network:
    driver: bridge

services:
  web:
    build:
      context: ./srcs/django
    # ports:  # This only was used for development!
    #   - "8000:8000"
    expose:
      - "8000"
    networks:
      - transcendence-backend
    volumes:
      - django_static:/app/static
      - django_media:/app/media:rw
      - ssl_certs:/tmp/ssl:ro
    depends_on:
      waf:
        condition: service_healthy
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - ./srcs/.env
    restart: always

  db:
    build:
      context: ./srcs/db
    expose:
      - "5432"
    networks:
      - transcendence-backend
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ssl_certs:/tmp/ssl:ro
    depends_on:
      waf:
        condition: service_healthy
    entrypoint:
      - /bin/bash
      - -c
      - |
        /usr/local/bin/get-vault-secrets.sh
        docker-entrypoint.sh postgres
    env_file:
      - ./srcs/.env
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  nginx:
    build:
      context: ./srcs
      dockerfile: nginx/Dockerfile
    expose:
      - "80"
      - "443"
      - "8443"
    networks:
      - transcendence-backend
      - app-network
    volumes:
      - type: volume
        source: nginx_static
        target: /usr/share/nginx/html
      - type: volume
        source: django_media
        target: /usr/share/nginx/html/media:rw
      - django_static:/usr/share/nginx/html/static:ro
      - ssl_certs:/tmp/ssl:ro
    depends_on:
      ssl-manager:
        condition: service_completed_successfully
      web:
        condition: service_started
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-k", "--fail", "-H", "Host: localhost", "https://localhost:8443/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  waf:
    build:
      context: ./srcs
      dockerfile: waf/Dockerfile
    ports:
      - "8082:8081"
      - "8445:8444"
      - "8200:8200"
    networks:
      - transcendence-backend
      - app-network
    volumes:
      - ssl_certs:/tmp/ssl:rw
      - waf_logs:/var/log/nginx
      - vault_data:/etc/vault.d/data
      - django_media:/usr/share/nginx/html/media:rw
      - ./srcs/waf/custom-nginx.conf.template:/etc/nginx/nginx.conf.template
    env_file:
      - ./srcs/.env
    command: >
      sh -c "envsubst '$$IP_SERVER' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf &&
             /usr/local/bin/vault-setup.sh"
    restart: always
    depends_on:
      ssl-manager:
        condition: service_completed_successfully
    healthcheck:
      test:
        - "CMD-SHELL"
        - "curl -k https://localhost:8200/v1/sys/health || curl -k --fail --max-time 1 http://localhost:8081/health || exit 0"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s

  redis:
    image: redis:latest
    expose:
      - "6379"
    networks:
      - transcendence-backend
    restart: always
    command: [ "redis-server", "--save", "", "--appendonly", "no" ]

  front:
    build: ./srcs/front
    container_name: front
    ports:
      - "3000:3000"
    volumes:
      - ./srcs/front:/app
    networks:
      - app-network
    restart: always

  ssl-manager:
    build:
      context: ./srcs/ssl
    volumes:
      - ssl_certs:/ssl:rw
    env_file:
      - ./srcs/.env
    networks:
      - transcendence-backend

volumes:
  django_media:
  django_static:
  nginx_static:
  waf_logs:
  ssl_certs:
    name: ssl_certs
  vault_data:
    driver: local
  postgres_data:
