#!/bin/bash

# Script para garantizar que el health check funcione correctamente
echo "[HEALTH_FIX] Configurando respuesta directa para health check..."

# Asegurar que nuestra configuración de health check tenga prioridad
cat > /etc/nginx/conf.d/000-health.conf << 'EOF'
# Health check priority configuration
# This file is generated by health_fix.sh

server {
    listen 8443 ssl;
    server_name localhost;
    
    # SSL config for health check server
    ssl_certificate /tmp/ssl/transcendence.crt;
    ssl_certificate_key /tmp/ssl/transcendence.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    location = /health {
        access_log off;
        add_header Content-Type text/plain;
        add_header X-Health-Source "health_fix.sh";
        return 200 'OK';
    }
}
EOF

echo "[HEALTH_FIX] Configuración de health check aplicada."

# También añadir la configuración al servidor principal para mayor seguridad
if [ -f /etc/nginx/conf.d/default.conf ]; then
    echo "[HEALTH_FIX] Verificando configuración en default.conf..."
    # Comprobar si ya existe una configuración de health
    if ! grep -q "location = /health" /etc/nginx/conf.d/default.conf; then
        echo "[HEALTH_FIX] Añadiendo configuración de health check a default.conf..."
        sed -i '/server_name localhost;/a \    location = /health {\n        access_log off;\n        add_header Content-Type text/plain;\n        add_header X-Health-Source "health_fix.sh";\n        return 200 "OK";\n    }' /etc/nginx/conf.d/default.conf
    fi
fi

echo "[HEALTH_FIX] Configuración completada."
exit 0
