#!/bin/bash

# Script to ensure health check works correctly
echo "[HEALTH_FIX] Configuring direct response for health check..."

# Create high-priority health check configuration
cat > /etc/nginx/conf.d/000-health.conf << 'EOF'
# Health check priority configuration
# This file is generated by health_fix.sh

server {
    listen 8443 ssl;
    server_name localhost;
    
    # SSL config for health check server
    ssl_certificate /tmp/ssl/transcendence.crt;
    ssl_certificate_key /tmp/ssl/transcendence.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    location = /health {
        access_log off;
        add_header Content-Type text/plain;
        add_header X-Health-Source "health_fix.sh";
        return 200 'OK';
    }
}
EOF

echo "[HEALTH_FIX] Health check configuration applied."

# Add health check configuration to the main server block for extra safety
if [ -f /etc/nginx/conf.d/default.conf ]; then
    echo "[HEALTH_FIX] Verifying configuration in default.conf..."
    # Check if health location already exists
    if ! grep -q "location = /health" /etc/nginx/conf.d/default.conf; then
        echo "[HEALTH_FIX] Adding health check configuration to default.conf..."
        sed -i '/server_name localhost;/a \    location = /health {\n        access_log off;\n        add_header Content-Type text/plain;\n        add_header X-Health-Source "health_fix.sh";\n        return 200 "OK";\n    }' /etc/nginx/conf.d/default.conf
    fi
fi

echo "[HEALTH_FIX] Configuration completed."
exit 0
