"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from django.core.management.utils import get_random_secret_key
import logging
from main.encryption import get_encryption_key

logger = logging.getLogger(__name__)

# Build base and root directory paths for Django project (main)
BASE_DIR = Path(__file__).resolve().parent.parent

# Basic project configuration
SECRET_KEY = os.environ.get("SECRET_KEY", get_random_secret_key())
DEBUG = os.environ.get("DEBUG", "True") == "True"

# Define allowed hosts in production (by default, no hosts allowed)
# ALLOWED_HOSTS = []
# ALLOWED_HOSTS = ['localhost', '127.0.0.1']

# Define installed applications in the project
INSTALLED_APPS = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "authentication",
    "authentication.fortytwo_auth",
    "channels",
    "chat",
    "tournament",
    "corsheaders",
    "game",
]

# Middleware configuration (intermediaries through which requests pass between client and application)
# Middleware executes in top-down order and is defined by default in Django
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",  # Security middleware
    "corsheaders.middleware.CorsMiddleware",  # CORS middleware
    "django.middleware.common.CommonMiddleware",  # Common middleware (for cookie handling)
    "django.middleware.csrf.CsrfViewMiddleware",  # CSRF protection middleware
    "django.contrib.sessions.middleware.SessionMiddleware",  # Session handling middleware
    "django.contrib.auth.middleware.AuthenticationMiddleware",  # User authentication middleware
    "django.contrib.messages.middleware.MessageMiddleware",  # Message handling middleware
    "django.middleware.clickjacking.XFrameOptionsMiddleware",  # Clickjacking protection middleware
    'authentication.middleware.UserSessionMiddleware',  # User activity tracking middleware
]

# CORS and Security configuration
CORS_ALLOW_METHODS = ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]
CORS_ALLOWED_ORIGINS = [
    "https://localhost:8445",
    "https://localhost:8443",
    "http://localhost:3000",
]
CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS + [
    "http://localhost:8082",
    "ws://localhost:8000",
    "wss://localhost:8445",
]

if DEBUG:
    ALLOWED_HOSTS = ["*"]
    CORS_ALLOW_ALL_ORIGINS = True
else:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1"]
    CORS_ALLOW_ALL_ORIGINS = False

# Template and static files configuration
ROOT_URLCONF = "main.urls"
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, "authentication/web/templates")
        ],  # Custom template directory (development)
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# ASGI = Asynchronous Server Gateway Interface
# It is a specification for communication between web servers and web applications or web application frameworks
ASGI_APPLICATION = "main.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("redis", 6379)],
        },
    },
}

# Database configuration
DATABASES = {
    "default": {
        "ENGINE": os.environ.get("SQL_ENGINE", "django.db.backends.sqlite3"),
        "NAME": os.environ.get("POSTGRES_DB", "db.sqlite3"),
        "USER": os.environ.get("POSTGRES_USER", "user"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "password"),
        "HOST": os.environ.get("SQL_HOST", "localhost"),
        "PORT": os.environ.get("SQL_PORT", "5432"),
    }
}

# Password validation for users (secure passwords)
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
    },  # Validate that the password is not similar to user attributes
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"
    },  # Validate that the password has a minimum length
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"
    },  # Validate that the password is not a common password
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"
    },  # Validate that the password contains at least one digit
]

# Internationalization and time zone settings
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# GDPR and Inactivity Settings - Time units in seconds for testing
# In production, these values should be set to days
TIME_MULTIPLIER = 86400  # 1 for testing (seconds), 86400 for production (days)

EMAIL_VERIFICATION_TIMEOUT = 10 * TIME_MULTIPLIER  # 1 second/day
INACTIVITY_THRESHOLD = 60 * TIME_MULTIPLIER     # 60 seconds/days
INACTIVITY_WARNING = 30 * TIME_MULTIPLIER       # 30 seconds/days
TASK_CHECK_INTERVAL = 2 * TIME_MULTIPLIER       # 2 seconds/days
SESSION_ACTIVITY_CHECK = 1 * TIME_MULTIPLIER  # 1 seconds/days

# Session settings for user activity tracking (middleware)
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = INACTIVITY_THRESHOLD * 2  # Double the inactivity threshold

# Celery Configuration
CELERY_BROKER_URL = 'redis://redis:6379/0'
CELERY_RESULT_BACKEND = 'redis://redis:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Celery configuration for handling connection retries
CELERY_BROKER_CONNECTION_RETRY = True
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BROKER_CONNECTION_MAX_RETRIES = 10
CELERY_WORKER_ENABLE_REMOTE_CONTROL = False
CELERY_WORKER_SEND_TASK_EVENTS = False

# Celery security configuration
CELERY_SECURITY_CONFIG = {
    'C_FORCE_ROOT': True,
}

# Worker configuration
CELERY_WORKER_CONFIG = {
    'worker_hijack_root_logger': False,
    'worker_max_tasks_per_child': 50,
    'worker_prefetch_multiplier': 1,
    'task_track_started': True,
    'worker_log_format': '[%(asctime)s: %(levelname)s] %(message)s',
    'worker_task_log_format': '[%(asctime)s: %(levelname)s] %(task_name)s - %(message)s',
    'worker_redirect_stdouts_level': 'ERROR',
}

# Beat configuration for periodic tasks
CELERY_BEAT_CONFIG = {
    'scheduler': 'django_celery_beat.schedulers:DatabaseScheduler',
    'max_interval': 300,  # 5 minutes
    'loglevel': 'WARNING',
}

# Celery periodic tasks configuration
CELERY_BEAT_SCHEDULE = {
    'cleanup-inactive-users': {
        'task': 'authentication.tasks.cleanup_inactive_users',
        'schedule': TASK_CHECK_INTERVAL,
    },
}

# Static and media files (images, videos, etc.)
# In production, these files should be served by NGINX
# and will be configured in the Nginx configuration file (comment or remove these lines)
STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static")
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
FILE_UPLOAD_PERMISSIONS = 0o644

# Static files configuration
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static_custom"),
]

# Static files (CSS, JavaScript, Images)
STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static_collected")
ADMIN_MEDIA_PREFIX = '/static/admin/'

# Eliminar o simplificar a solo Django admin
STATICFILES_APPS_ORDER = [
    'django.contrib.admin',
]

# Custom authentication configuration with CustomUser model defined in authentication.models
# We use CustomUser model instead of Django's default user model because we've added additional fields
# and modified authentication behavior to allow login with 42 or email
AUTH_USER_MODEL = "authentication.CustomUser"
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "user"
LOGOUT_REDIRECT_URL = "login"
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Environment variables for 42 authentication
FORTYTWO_CLIENT_ID = os.environ.get("FORTYTWO_CLIENT_ID")  #
FORTYTWO_CLIENT_SECRET = os.environ.get("FORTYTWO_CLIENT_SECRET")
FORTYTWO_REDIRECT_URI = os.environ.get("FORTYTWO_REDIRECT_URI")
FORTYTWO_API_UID = os.environ.get("FORTYTWO_API_UID")
FORTYTWO_API_SECRET = os.environ.get("FORTYTWO_API_SECRET")
FORTYTWO_API_URL = os.environ.get("FORTYTWO_API_URL")

# Environment variables for sending emails (SMTP)
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"  # Use this backend to print emails in the console
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'		# Use this backend to send real emails
EMAIL_HOST = os.environ.get("EMAIL_HOST")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", 587))
EMAIL_USE_TLS = (
    os.environ.get("EMAIL_USE_TLS") == "True"
)  # Use TLS to send emails (TLS is a secure version of SSL)
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL")
ACCOUNT_EMAIL_VERIFICATION = (
    "mandatory"  # Email address verification is required to activate the account
)

# Encryption key settings for GDPR compliance
ENCRYPTION_KEY = get_encryption_key()

# Frontend settings
FRONTEND_URL = "https://localhost:8445"
SITE_URL = FRONTEND_URL
EMAIL_VERIFICATION_URL = f"{FRONTEND_URL}/verify-email"

# Security settings
SECURE_BROWSER_XSS_FILTER = True
PASSWORD_RESET_TIMEOUT = 300
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"

# JWT token generation settings
JWT_SECRET_KEY = os.environ.get("JWT_SECRET_KEY", "default-secret-key")
JWT_ALGORITHM = os.environ.get("JWT_ALGORITHM", "HS256")
JWT_EXPIRATION_TIME = int(os.environ.get("JWT_EXPIRATION_TIME") or 3600)

# Logging configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "level": "DEBUG",
        },
    },
    "loggers": {
        "main.vault": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}
