"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from django.core.management.utils import get_random_secret_key
import logging
from django.core.signing import Signer
from cryptography.fernet import Fernet
import base64

logger = logging.getLogger(__name__)

# Build base and root directory paths for Django project (main)
BASE_DIR = Path(__file__).resolve().parent.parent

# Basic project configuration
SECRET_KEY = os.environ.get("SECRET_KEY", get_random_secret_key())
DEBUG = os.environ.get("DEBUG", "True") == "True"

# Define allowed hosts in production (by default, no hosts allowed)
# ALLOWED_HOSTS = []
# ALLOWED_HOSTS = ['localhost', '127.0.0.1']

# Define installed applications in the project
INSTALLED_APPS = [
    "daphne",
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "authentication",
    "authentication.fortytwo_auth",
    "channels",
    "chat",
    "tournament",
    "corsheaders",
    "game",
]

# Jazzmin configuration (custom admin panel based on Django Admin)
JAZZMIN_SETTINGS = {
    "site_title": "Pong Admin",
    "site_header": "Pong Administration",
    "welcome_sign": "Welcome to the Admin Panel",
    "show_ui_builder": True,
    "changeform_format": "horizontal_tabs",
}

# Middleware configuration (intermediaries through which requests pass between client and application)
# Middleware executes in top-down order and is defined by default in Django
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",  # Security middleware
    "corsheaders.middleware.CorsMiddleware",  # CORS middleware
    "django.middleware.common.CommonMiddleware",  # Common middleware (for cookie handling)
    "django.middleware.csrf.CsrfViewMiddleware",  # CSRF protection middleware
    "django.contrib.sessions.middleware.SessionMiddleware",  # Session handling middleware
    "django.contrib.auth.middleware.AuthenticationMiddleware",  # User authentication middleware
    "django.contrib.messages.middleware.MessageMiddleware",  # Message handling middleware
    "django.middleware.clickjacking.XFrameOptionsMiddleware",  # Clickjacking protection middleware
]

# CORS and Security configuration
CORS_ALLOW_METHODS = ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]
CORS_ALLOWED_ORIGINS = [
    "https://localhost:8445",
    "https://localhost:8443",
    "http://localhost:3000",
]
CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS + [
    "http://localhost:8082",
    "ws://localhost:8000",
    "wss://localhost:8445",
]

if DEBUG:
    ALLOWED_HOSTS = ["*"]
    CORS_ALLOW_ALL_ORIGINS = True
else:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1"]
    CORS_ALLOW_ALL_ORIGINS = False

# Template and static files configuration
ROOT_URLCONF = "main.urls"
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, "authentication/web/templates")
        ],  # Custom template directory (development)
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# ASGI = Asynchronous Server Gateway Interface
# It is a specification for communication between web servers and web applications or web application frameworks
ASGI_APPLICATION = "main.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("redis", 6379)],
        },
    },
}

# Database configuration
DATABASES = {
    "default": {
        "ENGINE": os.environ.get("SQL_ENGINE", "django.db.backends.sqlite3"),
        "NAME": os.environ.get("POSTGRES_DB", "db.sqlite3"),
        "USER": os.environ.get("POSTGRES_USER", "user"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "password"),
        "HOST": os.environ.get("SQL_HOST", "localhost"),
        "PORT": os.environ.get("SQL_PORT", "5432"),
    }
}

# Password validation for users (secure passwords)
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
    },  # Validate that the password is not similar to user attributes
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"
    },  # Validate that the password has a minimum length
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"
    },  # Validate that the password is not a common password
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"
    },  # Validate that the password contains at least one digit
]

# Internationalization and time zone settings
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# Static and media files (images, videos, etc.)
# In production, these files should be served by NGINX
# and will be configured in the Nginx configuration file (comment or remove these lines)
STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static")
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
FILE_UPLOAD_PERMISSIONS = 0o644

# Custom authentication configuration with CustomUser model defined in authentication.models
# We use CustomUser model instead of Django's default user model because we've added additional fields
# and modified authentication behavior to allow login with 42 or email
AUTH_USER_MODEL = "authentication.CustomUser"
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "user"
LOGOUT_REDIRECT_URL = "login"
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Environment variables for 42 authentication
FORTYTWO_CLIENT_ID = os.environ.get("FORTYTWO_CLIENT_ID")  #
FORTYTWO_CLIENT_SECRET = os.environ.get("FORTYTWO_CLIENT_SECRET")
FORTYTWO_REDIRECT_URI = os.environ.get("FORTYTWO_REDIRECT_URI")
FORTYTWO_API_UID = os.environ.get("FORTYTWO_API_UID")
FORTYTWO_API_SECRET = os.environ.get("FORTYTWO_API_SECRET")
FORTYTWO_API_URL = os.environ.get("FORTYTWO_API_URL")

# Environment variables for sending emails (SMTP)
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"  # Use this backend to print emails in the console
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'		# Use this backend to send real emails
EMAIL_HOST = os.environ.get("EMAIL_HOST")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", 587))
EMAIL_USE_TLS = (
    os.environ.get("EMAIL_USE_TLS") == "True"
)  # Use TLS to send emails (TLS is a secure version of SSL)
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL")
ACCOUNT_EMAIL_VERIFICATION = (
    "mandatory"  # Email address verification is required to activate the account
)

# Frontend settings
FRONTEND_URL = "https://localhost:8445"
SITE_URL = FRONTEND_URL
EMAIL_VERIFICATION_URL = f"{FRONTEND_URL}/verify-email"

# Security settings
SECURE_BROWSER_XSS_FILTER = True
PASSWORD_RESET_TIMEOUT = 300
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"

# JWT token generation settings
JWT_SECRET_KEY = os.environ.get("JWT_SECRET_KEY", "default-secret-key")
JWT_ALGORITHM = os.environ.get("JWT_ALGORITHM", "HS256")
JWT_EXPIRATION_TIME = int(os.environ.get("JWT_EXPIRATION_TIME") or 3600)

# Logging configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "level": "DEBUG",
        },
    },
    "loggers": {
        "main.vault": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,  # Custom logger for vault app
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}

# Generate encryption key for email encryption using Fernet before starting the Django app
# The key is used to encrypt email addresses in the database
# The key is generated using the Django Signer class
try:
    signer = Signer()
    key_base = signer.sign(SECRET_KEY).encode()
    key_32 = base64.urlsafe_b64encode(key_base[:32].ljust(32, b'0'))
    ENCRYPTION_KEY = key_32
    logger.info("ENCRYPTION_KEY generated successfully")
except Exception as e:
    logger.error(f"Error generating ENCRYPTION_KEY: {str(e)}")
    # Generate a fallback key if the main key generation fails
    ENCRYPTION_KEY = Fernet.generate_key()
    logger.info("Generated fallback ENCRYPTION_KEY")
