#!/bin/bash

# This is the main script that orchestrates the entire configuration process.
# Responsibilities:
# - Loading required modules
# - Coordinating initialization sequence
# - Dependency validation
# - Global error handling
# - Cleanup of sensitive variables

# Define modules path
MODULES_PATH="/usr/local/bin"
REQUIRED_MODULES=(
    "${MODULES_PATH}/logger.sh"
    "${MODULES_PATH}/vault-config.sh"
    "${MODULES_PATH}/vault-init.sh"
    "${MODULES_PATH}/vault-secrets.sh"
)

# Verify and load modules
for module in "${REQUIRED_MODULES[@]}"; do
    if [ ! -f "$module" ]; then
        echo "Error: Required module not found: $module"
        exit 1
    fi
    source "$module"
done

# Ensure SSL directory exists and has proper permissions
ensure_ssl_dir() {
    echo "Ensuring SSL directory exists with proper permissions..."
    
    # Create directory with root permissions
    mkdir -p /tmp/ssl || true
    
    # Set permissions for all users
    chmod -R 777 /tmp/ssl || true
    
    # Wait for SSL certificates to be generated by ssl-manager
    local max_attempts=30
    local attempt=1
    
    while [ $attempt -le $max_attempts ]; do
        if [ -f "/tmp/ssl/transcendence.crt" ] && [ -f "/tmp/ssl/transcendence.key" ]; then
            log_message "SSL certificates found"
            # Make sure certificates are readable by all
            chmod 644 /tmp/ssl/transcendence.crt || true
            chmod 644 /tmp/ssl/transcendence.key || true
            return 0
        fi
        
        log_message "Waiting for SSL certificates... (Attempt $attempt/$max_attempts)"
        attempt=$((attempt + 1))
        sleep 2
    done
    
    log_message "WARNING: SSL certificates not found, will generate locally"
    /usr/local/bin/generate-ssl.sh || echo "Failed to generate SSL certificates"
    return 0
}

# Main setup function
setup() {
    # Ensure SSL directory exists and has proper permissions
    ensure_ssl_dir
    
    # Start Vault server (vault-init.sh)
    start_vault
    
    # Initialize and unseal Vault (vault-init.sh)
    initialize_vault
    
    # Configure Vault and policies (vault-init.sh)
    configure_vault
    
    # Store secrets (vault-secrets.sh)
    store_secrets
    
    # Keep vault running in foreground
    log_message "Vault setup complete. Keeping vault running in foreground..."
    tail -f /dev/null
}

# Run setup
setup
