# Generated by Django 5.1.3 on 2024-11-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fortytwo_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
